### ISSUE TITLE
Right side alignment in the"Current" menu

### ISSUE THREAD

**Issue by MrBabach** [CatcherITGF/NX-Venom#12]
It would be nice to make the right side alignment for values in the "Current" menu

![photo_2024-09-06_22-55-12](https://github.com/user-attachments/assets/b7baf883-f60e-4fdc-b7de-e8dafe61410c)

**Comment by CatcherITGF** [comment]
Uberhand devs repo: https://github.com/efosamark/Uberhand-Overlay
