### ISSUE TITLE
DBI won't enable USB 3.0

### ISSUE THREAD

**Issue by jmpangilinan** [CatcherITGF/NX-Venom#15]
In DBI MTP Responder, it only shows USB 2.0 even though I connected to a USB 3.0 port with a USB 3.0 capable cable.

I checked in **system_settings.ini** in atmosphere

> [usb]
> usb30_force_enabled=u8!0x1

Also I tried to put in **hekate_ipl.ini**

> usb3force=1

```
[config]
autoboot=1
autoboot_list=0
bootwait=3
backlight=40
autohosoff=2
autonogc=0
updater2p=0
bootprotect=0
{}

[CFW (emuMMC)]
emummcforce=1
fss0=atmosphere/package3
cal0blank=1
kip1=atmosphere/kips/loader.kip
icon=bootloader/res/icon_atmosphere.bmp
usb3force=1
{}

[CFW (SysNAND)]
emummc_force_disable=1
fss0=atmosphere/package3
cal0blank=0
kip1=atmosphere/kips/loader.kip
icon=bootloader/res/icon_semistock.bmp
usb3force=1
{}

[Stock (SysNAND)]
emummc_force_disable=1
fss0=atmosphere/package3
cal0blank=0
stock=1
icon=bootloader/res/icon_stock.bmp
usb3force=1
{}
```

then rebooted my console and pc, still it shows USB 2.0.

**Comment by CatcherITGF** [comment]
![2024-11-05_00-50-13](https://github.com/user-attachments/assets/a7b4ef51-c022-497b-bade-867daa80dcd4)

**Comment by CatcherITGF** [comment]
Works out of box. Either your port is incompatible with USB 3, or the cable.

**Comment by jmpangilinan** [comment]
> Works out of box. Either your port is incompatible with USB 3, or the cable.

Hmm very weird, my USB port is 3.0 because it has a SS tag and is colored blue, I have tried to plug a 3.0 gigabit ethernet and it does give full speed of 1Gbps. I also tried plugging my switch to different computers with USB 3.0 port, but it still shows 2.0, also tried different cables (blue colored and orange colored ones).

**Comment by jmpangilinan** [comment]
Upon more research, I found out my cable is not 3.0 capable by counting its pins (4 pins) as 3.0 has 9 pins, though my phone has USB-C 3.2 out of the box, I didn't know that the cable came with it is not 3.0 capable.
