### ISSUE TITLE
Switch sometimes doesn't wake up from sleep

### ISSUE THREAD

**Issue by inspectah88** [CatcherITGF/NX-Venom#17]
I recently updated from last pre AMS 1.8.0 version (4.13.1) to newest version and since then sometimes the Switch doesn't wake up from sleep mode and I have to hard reset.

This happened on FW 18.1.0 and on 19.0.1 too.
Is this a known bug?

**Comment by CatcherITGF** [comment]
Most likely, some system module is not compatible with the latest AMS. I recommend renaming the contents folder as a backup, installing the update again via AIO and checking if there will be a problem. If it is decided, then calculate by the exclusion method which of the sysmodules breaks the sleep, and then check if there are updates on it. All modules included in Venom are exactly compatible, but you may have your owns.

**Comment by inspectah88** [comment]
Thanks.
I compared my contents folder to your latest package and I have everything up-2-date.
Only folder I don´t know where its coming from is 0100000000001013, I removed it.
Do you know what it´s for?

It´s difficult to test, because it only happens sometimes.
Perhaps it´s my kip file, but I´m using the same OC settings for months without problems.

**Comment by EvilPanda666** [comment]
> Thanks. I compared my contents folder to your latest package and I have everything up-2-date. Only folder I don´t know where its coming from is 0100000000001013, I removed it. Do you know what it´s for?
> 
> It´s difficult to test, because it only happens sometimes. Perhaps it´s my kip file, but I´m using the same OC settings for months without problems.

0100000000001013 is [MissionControl](https://github.com/ndeadly/MissionControl) for using non Switch controllers over Bluetooth. Latest version is v0.12.0 which only provides support up to firmware v19.0.

Make sure you're not using an old system_settings.ini. I know that NX-Venom occasionally makes changes to it. Could be a setting that's enabled on an old config. Something like `Background processing = u8!0x0 (shutdown directly when entering sleep mode)` comes to mind which will turn off sleep mode forcing you to reboot after a few minutes once the screen is turned off.

**Comment by inspectah88** [comment]
Hmm, I never used custom themes and am very cautious what I install.
Venom is the first AIO pack that I use.

I'm using now the system_settings.ini from Venom, it has the same settings for cheats like mine did.

I didn't have the problem in the last days.
So even if I don't know what it was causing it, I think you can close the issue.

Thanks for the help.
