### ISSUE TITLE
What was the default mem freq for Erista changed to in v4.1.1? 

### ISSUE THREAD

**Issue by Atheneouz** [CatcherITGF/NX-Venom#6]
Wondering what the default mem freq was changed to before I update because my v1 Switch is unable to clock 1862MHz without immediately crashing. Is it possible to add more frequencies between 1600MHz and 1862MHz? 

Thanks

**Comment by CatcherITGF** [comment]
This is due to the fact that 1862MHz does not work stably on some consoles. I recommend raising the frequency up to 1996, this should help. By the way, juts update NX-Venom to the latest version via AIO Updater, 1996 is already there by default.

**Comment by Atheneouz** [comment]
Okay, thanks. I updated and tried 1996, but sadly it's still glitching out when I select it. I also tried raising EMC Vdd2 and EMC DVB shift but no luck.

**Comment by CatcherITGF** [comment]
Try lowering the timings to zero. If it works without glitches, then raise one by one.

**Comment by Atheneouz** [comment]
Thanks so much, that worked! I left T1 T2 T3 at their defaults. T4 was dropped from 2 to 1, seems like that was causing the issue.
T1 = 15
T2 = 15
T3 = 34
T4 = 1
T5 = 3
T6 = 3
T7 = 5
T8 = 2
T9 = 2
Are these timings okay? I've only raised the ones I can, back to what they were before. Should I aim to have them as high as they can go?

**Comment by CatcherITGF** [comment]
Nice. Thanks for the info. I will adjust the default kip. Don't worry, T4 does not provide significant performance.
