### ISSUE TITLE
LineageOS compatibility (hekate v4 update) 

### ISSUE THREAD

**Issue by youngkong10** [CatcherITGF/NX-Venom#9]
Hello, just wondering if you will update the hekate to 6.2.0 v4 to make it compatible with switchroot lineageos. Also thanks for everything you do for this project it is the best.

**Comment by CatcherITGF** [comment]
Fixed, [release 4.5.1](https://github.com/CatcherITGF/NX-Venom/releases/tag/4.5.1)
Thanks for feedback.
